### ISSUE TITLE
[Feat] 기본 Widget 구성

### ISSUE THREAD

**Issue by commitcomplete** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#110]
### 문제 상황
- 크기에 따른 위젯 콘텐츠 구성
- 크기는 1,2,3이 있고 일단 1의 크기에 대한 실수노트로 이동하는 위젯을 생성하겠다.

### TODO
- [x] 위젯 UI 구성
- [x] 실수노트 내용 앱에서 받아오기
- [x] 실수노트 클릭시 실수노트 탭으로 이동하기
