### ISSUE TITLE
[Fix] AddPrimaryPillView, ManageDosingView 피드백 반영

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#113]
### 문제 상황

- 복용 리스트 정렬이 필요
- 유저마다 약물 용량을 기입하는 방식이 다름. 특히 약물 용량을 넣을 때 단위를 생략하는 경우가 많음

### TODO

- [ ] 토글이 켜져있는 경우 상단으로 올라오도록 복용 리스트 정렬 (ManageDosingView) -> 이슈 #155 
- [x] 약물 용량의 키보드를 숫자 키보드로 변경
- [x] mg / 정과 같은 단위 설정을 위한 segmented control 혹은 picker 추가
