### ISSUE TITLE
[Feat] 환경설정 페이지 추가

### ISSUE THREAD

**Issue by mycookie1** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#114]
### 문제 상황
- 알림, 버전정보 등 이전에 담지 못한 정보를 설정탭을 추가하여 해결

### TODO
- [x] 설정탭 연결
- [x] 설정페이지에서 테이블 뷰 생성
- [x] 테이블 뷰에서 각 페이지로 네비게이션 설정
- [x] 문의사항 페이지에서 메일기능 추가
- [x] 버전확인 페이지에서 버전체크 후 업데이트기능
- [x] 알림기능 연결
