### ISSUE TITLE
[Feat] 설정페이지 테이블 추가

### ISSUE THREAD

**Issue by mycookie1** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#119]
### 문제 상황
-  설정페이지 

### TODO
- [x] 설정페이지, 기능 테이블 구현
- [x] 글자가 ... 으로 나오는 것 해결
- [x] 스타일, 오토레이아웃 적용
<img width="325" alt="image" src="https://user-images.githubusercontent.com/103025266/181432779-cc90c74c-8bb5-443e-99a5-65f4d11c7b99.png">
