### ISSUE TITLE
[Feat] 워치에서 폰으로 복약기록, 컨디션 데이터 전송하기

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#125]
### 문제 상황
- 

### TODO
- [x] 복약기록 뷰 작성하기
- [x] 복약기록 데이터 전송하기
- [x] 복약취소 데이터 전송하기 
- [x] 컨디션기록 뷰 작성하기
- [x] 컨디션기록 데이터 전송하기
- [x] 폰에서 워치도 복약 데이터 전송하기
