### ISSUE TITLE
[Feat] 메인 약 추가 화면 UI 구현

### ISSUE THREAD

**Issue by 2youngjun** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#13]
### 문제 상황
- 메인 약 추가 화면 UI 를 구현한다.

### TODO
- [ ] Half Modal
- [ ] 약 이름 / 용량 / 복약 간격(아침, 점심, 저녁) Stack View 관리
- [ ] 각 Vertical Stack View 에 내용 기입 시 변경되는 UI 구현
- [ ] 취소 / 저장 버튼 구현

**Comment by 2youngjun** [comment]
+ 취소 버튼 구현
+ 저장 버튼은 #27 과 함께 구현
