### ISSUE TITLE
[Fear] 달력에 들어갈 함수 구현

### ISSUE THREAD

**Issue by mycookie1** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#143]
### 문제 상황
- 약복용 여부, 부작용 기록여부, 기타 증상을 기록하기 위한 함수필용

### TODO
- [x] 약복용 여부 여부 함수
- [x]  부작용 기록 여부 함수
- [x] 기타 증상 기록 여부 함수
