### ISSUE TITLE
[Feat] 서브 약 추가 화면 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#15]
### 문제 상황
- 서브 약 추가 화면 구현 필요

### TODO
- [x] 모달 뷰 띄우기
- [x] SearchField와 TableView UI 추가
- [x] 테이블에 검색된 약 이름 리스트 보여주기
- [x] 현재 입력한 약 이름에 대한 약 추가하기 버튼 추가
