### ISSUE TITLE
[Feat] 날짜를 바꿨을 때 약 복용 토글, 네비게이션 비활성화 , 시간 수정 가능하게 

### ISSUE THREAD

**Issue by mycookie1** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#160]
### 문제 상황
- 이전 날짜로 갔을 때, 약 먹은 것을 기록하고 싶은데 현재 막혀있음
- 네비게이션으로 더 추가하는 것은 막고 오늘 날짜에 등록된 약만 복용 가능하게 수정
- 현재 복용 시간 수정이 불가능함

### TODO
- [x] 이전 날짜로 갔을 때 네비게이션 비활성화
- [x] 오늘의 약 이라는 워딩을 날짜 정도로 바꾸기
- [x] 이전 날짜의 약 복용가능하게 함수 수정
- [x] 시간 수정 함수 구현
