### ISSUE TITLE
[Feat] AddsecondaryPillViewn 수정

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#166]
### 문제 상황
- 디자인 통일성

### TODO
- [x] 취소버튼 초록색으로 수정
- [x] 약 추가하기 내용 없을 때, 보이지 않도록 수정
- [x] 약 추가하기 버튼 작게 수정
- [x] 약 추가하기 버튼 초록색으로 변경
