### ISSUE TITLE
[Fix] SettingView 수정

### ISSUE THREAD

**Issue by mycookie1** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#168]
### 문제 상황
- 

### TODO
- [x]  S - 기능, 정보 라벨 타이틀 느낌으로 (ref. medicationView 오늘 복용할 약이에요)
- [x]  F - 디테일 뷰 들어갔을 때 탭바 숨기기
- [x]  C - 코코아팟 라이센스 추가
- [x]  B - 설정 네비게이션 기본 바, 커스텀 바 겹침 현상
