### ISSUE TITLE
[Feat] MedicationView 뷰 수정

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#169]
### 문제 상황
- 

### TODO
**Medication View**
- [x] 워딩 수정
  - 과거 날짜 선택시: 오늘 복용할 약이에요 → NN일에 복용한 약이예요
  - 복용관리 → 약 등록
- [x] 이전 날짜에서 증상입력 비활성화
- [x] 이전 날짜에서 복용관리 비활성화
**Condition View**
- [x] 증상입력 뷰에서 스크롤 인디케이터 제거
