### ISSUE TITLE
[Feat] MedicationView(Main) UI

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#17]
### 문제 상황
- MedicationView의 Primary Pill 복용 영역 필요 -> Main 전체 UI로 변경

### TODO
- [ ] 목업 데이터
- [x] 증상기록 버튼
- [x] Primary Pill View, TableView
- [x] Secondary Pill View, TableView
- [x] 버튼과 다른 작업자들의 View들을 연결
