### ISSUE TITLE
[Fix] Notification 수정

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#182]
### 문제 상황
- 알림 관련 문제 수정

### TODO
- [ ] 먹을 약이 있을 때에만 알림이 울리도록 -> 시도하되, 우선순위 낮음
- [ ] 약을 먹었다면 알림 x
- [ ] 실수노트 알림 -> 에필로그 알림 워딩 수정
