### ISSUE TITLE
[Fix] MainView

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#184]
### 문제 상황
- 메인뷰의 종합적인 기능 추가 및 버그 해결

### TODO
- [x] 복용해야할 약이 없거나 모든 약을 복용했을 시 전체 복용 버튼 비활성화
- [x] 이전 날짜 메인약 회색 처리 대신 isHidden으로 수정
- [x] 날짜 수정 기능 추가 (+하프모달 커스텀으로 수정)
- [x] 약 이름 길어지면 복용시간 안나오는 문제 해결
- [x] 약 복용 취소눌렀을 때 alert 띄워주는 기능 추가 (추가약 복용도 마찬가지)
- [x] 증상기록 버튼 수정
