### ISSUE TITLE
[Feat] watch에서 약 개별 복용 버튼 추가

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#190]
### 문제 상황
- watch에서 전체 복용만 가능하도록 구현되어있음

### TODO
- [x] 약 개별 복용버튼 추가한 뷰 짜기
- [x] 워치와 폰 Connectivity 연결하기
- [x] 날짜가 지났을 때 데이터 새로 만들어서 넣어주기
- [x] ShowPrimaryPill이 워치에 들어온 날짜와 상관없이 휴대폰에서 데이터 처리가 가능하도록 만들기
