### ISSUE TITLE
[Feat] 서브약 복약 기록 카드 뷰 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#21]
### 문제 상황
- MedicationView에 서브약 복약 기록 카드 UI 및 동작 구현

### TODO
- [x] 메인약 복약 기록 카드 재사용하여 카드 뷰 구현
- [x] 서브약 추가하기 모달뷰 호출 버튼 추가
- [x] 모달뷰에서 입력한 데이터 받아와 뷰 업데이트 구현
