### ISSUE TITLE
[Feat] 이전 날짜에서 메인 약 추가 기능 구현

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#216]
### 문제 상황
- 이전 날짜로 돌아갔을 때 현재 추가약, 메인약 모두 추가 불가능함.
- 둘 다 추가할 수 있도록 수정 필요
- 메인약의 경우, 기존 메인 뷰 추가 화면이 아니라 하프모달을 통해 구현! 
    - Date에 따라 IBAction을 분기해야함.

### TODO
- [x] 메인약 추가 코어데이터 함수 수정
- [x] Date 상태에 따른 IBAction 분기 처리
- [x] 모달을 통해 메인약 추가 기능 구현
