### ISSUE TITLE
[Feat] 메인약 추가 뷰 수정

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#217]
### 문제 상황
- 하프모달로 되어있는 메인약 뷰가 너무 좁음
- 풀 모달로 변경 필요
- 현재 드롭다운 내에 없는 약은 추가 불가 -> 드롭다운에 직접추가 셀 추가 필요

### TODO
- [x] 모달을 풀모달로 변경
- [x] 드롭다운의 삼각형 모양을 아래로 향하도록 수정
- [x] 하단 여백이 너무 크지 않도록 조정
- [x] 약 직접 추가 기능 필요
