### ISSUE TITLE
[Feat] 복약방식 추가 뷰 UI 추가

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#37]
### 문제 상황
- 메인약 복약방식 추가 뷰 구현 필요

### TODO
- [x] 복용 관리 버튼으로 네비게이션으로 뷰 호출
- [x] 복약방식 추가 버튼으로 "복약방식 추가하기" 하프모달 뷰 호출
- [x] 테이블 뷰 구성
- [x] 커스텀테이블뷰 셀로 [약 이름, 용량, 시간대, 토글버튼] 담기
