### ISSUE TITLE
[Feat] 히스토리 뷰 UI 구현

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#6]
### 문제 상황
- 사용자가 입력한 정보 (약 복용 및 증상)를 한 번에 보여주는 화면 구현
- 구현해야 할 화면
<img src = "https://user-images.githubusercontent.com/68676844/179365942-bf29d3ab-2c1d-4ef5-b081-cb9c1ea810b2.png" width = 250>

### TODO
- [x] TableView 구현
- [x] TableView 모양 변경
- [x] 데이터 종류에 맞춰 Cell 크키 변경
- [x] coredata 형식에 맞춰 뷰 크기 변경되는지 확인
