### ISSUE TITLE
[Feat] 메인약 복약기록 카드 뷰 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#62]
### 문제 상황
- 

### TODO
- [x] TableView와 Custom TableViewCell UI 짜기 (@yeniful)
- [x] Primary TabeView에 코어데이터 연결
- [x] 복약관리 뷰에서 복약방식 추가/수정/삭제시 정상적으로 반영
- [x] 복약 버튼을 누르면 히스토리로 데이터 저장
- [x] 복약 취소하면 히스토리에서 해당 데이터 삭제
