### ISSUE TITLE
[Fix] 서브약 복용 취소가 안되는 버그

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#75]
### 문제 상황
- MedicationView의 서브약 복용 버튼 누른 뒤에 다시 버튼을 눌렀을 때 체크 해제가 안되는 문제

### TODO
- [ ] 서브약 복용 버튼을 눌렀을 때 정상적으로 복용 취소 기능 작동시키기
- [ ] 서브약 복용 버튼을 눌렀을 때 히스토리에서 복용한 서브약 기록 제거하기
- [ ] 복용 버튼을 누르면 캡션에 각 서브약 복약 시간 기록하기
