### ISSUE TITLE
[Feat] 서브약 복용 기록 뷰, 셀 레이아웃 수정

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#76]
### 문제 상황
- 서브약 복용 기록 뷰 하단에 셀 하나 높이의 여백 발생 (아마, 메인약의 전체 복용 버튼의 공간이 서브약에 그대로 남아있는게 아닐까 조심스레 추측해봅니다)
- 서브약 셀에서 약 이름의 길이가 길어지는 경우에, 버튼 뒤로 글자가 넘어가버리는 문제 발생
- 이름이 길어지는 경우, 이에 맞춰 복약 시간을 수정하는 연필 아이콘도 함께 뒤로 넘어가버리는 문제 발생
<img width="496" alt="image" src="https://user-images.githubusercontent.com/39216546/180651482-b91b08bb-a921-43dc-a245-82e53df4660e.png">

### TODO
- [x] 서브약 복용 기록 뷰 하단의 여백 제거
- [x] 서브약 셀의 약 이름 길이 제한 (넘어가는 글자에 대해 ... 표시 등)
- [x] 연필 아이콘 위치를 고정하기 -> fade out
