### ISSUE TITLE
[Feat] 서브약 복용기록 취소 기능

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#81]
### 문제 상황
- 서브약 복용 후 버튼을 다시 눌렀을 때 취소가 되어야 한다.

### TODO
- [x] 버튼 한번 더 클릭 시 UI 복용버튼으로 변경
- [x] CoreData에서 해당 context 삭제
- [x] 메인약 추가 시 완료버튼 활성화 기능 수정
