### ISSUE TITLE
[Feat] MainView design 수정

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APilLog#83]
### 문제 상황
- 추가 설정 화면으로 전환하는 부분이 명확하지 않음 -> 텍스트로 표기
- 시간 수정 기능이 없기 때문에 관련된 부분을 삭제한다. (혼란을 야기할 수 있기 때문)
- 전체복용 버튼 사이즈, 텍스트 사이즈 변경
- 추가약 기록 부분 여백 제거

|현재 화면| 바뀌어야할 부분|
|---|---|
|<image src = "https://user-images.githubusercontent.com/68676844/180732362-ff0ddaba-28dc-4d2c-889d-69f0452d3ad0.png" width = 250> | <image src = "https://user-images.githubusercontent.com/68676844/180732849-8c561250-7000-4862-96e2-15134fa8b56a.png" width=250>|
|<img src = "https://user-images.githubusercontent.com/68676844/180736424-9b900978-26cd-407e-b9cf-224d49b9b5ab.png" width = 250>| <img src ="https://user-images.githubusercontent.com/68676844/180737385-59e73d5d-8c99-401d-aa65-fb7e7c22e164.png" width = 250>|

<img src = "https://user-images.githubusercontent.com/68676844/180737958-197c9faf-a4cb-4638-9e95-b32177f3175e.png" width = 250>

### TODO
- [x] 추가하기, 설정하기라는 텍스트 추가하기
- [x] 아직 복약 전이에요, 수정버튼(연필모양) 삭제하기
- [x] 전체복용 버튼 사이즈, 텍스트 사이즈 변경
- [x] 추가약 기록 부분 여백 제거
- [x] 메인 뷰 background color 변경 (뭔가 달라보여요!)
