### ISSUE TITLE
[Feat] DiaryView 수정

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC3-Team2-APillog#89]
### 문제 상황
- [실수노트 메인 화면] 여백이 너무 많아 에러가 있는 화면처럼 보임
- [실수노트 작성 화면] "오늘은.."이라는 디폴트 텍스트 제거 
- [실수노트 작성 화면] "저장하고 훌훌 털어버리기" 버튼의 width를 회색 박스의 width와 일치시키기
- [실수노트 작성 화면] Date picker tintcolor 변경

|현재 뷰| 수정 후 보일 화면|
|---|---|
|<img src = "https://user-images.githubusercontent.com/68676844/180759185-ba1ac5d5-d804-4681-8e65-127daa2670d0.png" width=250>|<img src = "https://user-images.githubusercontent.com/68676844/180759465-b747fe0c-fa16-4a65-9d4b-cf3151aa7188.png" width = 250>|
<img src ="https://user-images.githubusercontent.com/68676844/180760590-1834a6ea-d19e-4589-bd0e-eeb58a8fabb4.png" width = 250>
<img src = "https://user-images.githubusercontent.com/68676844/180760622-e8eeb1cc-26d9-4f16-a575-87665dde9a30.png" width = 250

### TODO
- [ ] 컨텐츠 내용에 따라 테이블 뷰의 높이가 수정되도록 구현
- [x] 실수노트에 아무것도 없을 때 "아직 작성된 실수노트가 없어요"라는 뉘앙스의 문구 작성하여 띄우기
- [x] "오늘은.." 텍스트 제거
- [x] 저장버튼 크기 조절
- [x] 데이트픽커 색상 포인트 컬러로 변경

**Comment by commitcomplete** [comment]
Thankyou Soi~
